### ISSUE TITLE
Plugin uses nightly even when nightly-msvc is installed and nightly isn't

### ISSUE THREAD

**Issue by LaylBongers** [koute/parcel-plugin-cargo-web#10]
Building works fine on `nightly-msvc` and for various reason I don't really want to switch toolchain, perhaps use the `default` toolchain instead?
In general I would rather this plugin not mess with my rustup instal, don't even try to update it, and just ask me to install missing things instead. Updating especially can cause problems because certain components may not be available in the latest nightly, such as `rls-preview`.

**Comment by koute** [comment]
I would like to keep it mostly automatic (to keep with the general feel of Parcel), however I agree that it'd be better if it wouldn't try to update and perhaps use a preset nightly version (e.g. something similar to https://github.com/koute/parcel-plugin-cargo-web/pull/9) so the rest of your toolchain would stay unmolested. (This is also a good idea due to the fact that `nightly` sometimes breaks, unfortunately.)
